import { NextResponse } from 'next/server'
import { getPayload } from 'payload'
import config from '@payload-config'
import { headers as getHeaders, cookies } from 'next/headers'

/**
 * POST /api/shared-links
 * Create a new shared link for curated search results
 */
export async function POST(request: Request) {
    try {
        const payload = await getPayload({ config })

        // Get the current user from the request
        const headersList = await getHeaders()
        const cookieStore = await cookies()
        const token = cookieStore.get('payload-token')?.value

        if (!token) {
            return NextResponse.json(
                { error: 'Authentication required' },
                { status: 401 }
            )
        }

        // Verify the user
        const { user } = await payload.auth({ headers: headersList })

        if (!user) {
            return NextResponse.json(
                { error: 'Invalid authentication' },
                { status: 401 }
            )
        }

        const body = await request.json()
        const { title, filters } = body

        if (!title || !filters) {
            return NextResponse.json(
                { error: 'Title and filters are required' },
                { status: 400 }
            )
        }

        // Create the shared link
        const sharedLink = await payload.create({
            collection: 'shared-links',
            data: {
                title,
                filters,
                createdBy: user.id,
                slug: '', // Will be auto-generated by hook
            },
            draft: false,
        })

        // Generate the shareable URL
        const baseUrl = process.env.NEXT_PUBLIC_SERVER_URL || 'http://localhost:3000'
        const shareUrl = `${baseUrl}/shared/${sharedLink.slug}`

        return NextResponse.json({
            success: true,
            shareUrl,
            sharedLink: {
                id: sharedLink.id,
                slug: sharedLink.slug,
                title: sharedLink.title,
            },
        })
    } catch (error) {
        console.error('Error creating shared link:', error)
        const errorMessage = error instanceof Error ? error.message : 'Unknown error'
        return NextResponse.json(
            { error: `Failed to create shared link: ${errorMessage}` },
            { status: 500 }
        )
    }
}

/**
 * GET /api/shared-links
 * Get all shared links for the current user
 */
export async function GET() {
    try {
        const payload = await getPayload({ config })

        const headersList = await getHeaders()
        const cookieStore = await cookies()
        const token = cookieStore.get('payload-token')?.value

        if (!token) {
            return NextResponse.json(
                { error: 'Authentication required' },
                { status: 401 }
            )
        }

        const { user } = await payload.auth({ headers: headersList })

        if (!user) {
            return NextResponse.json(
                { error: 'Invalid authentication' },
                { status: 401 }
            )
        }

        // Get shared links created by this user
        const sharedLinks = await payload.find({
            collection: 'shared-links',
            where: {
                createdBy: { equals: user.id },
            },
            sort: '-createdAt',
            limit: 100,
        })

        return NextResponse.json({
            success: true,
            sharedLinks: sharedLinks.docs,
        })
    } catch (error) {
        console.error('Error fetching shared links:', error)
        return NextResponse.json(
            { error: 'Failed to fetch shared links' },
            { status: 500 }
        )
    }
}
