/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    provinces: Province;
    cities: City;
    barangays: Barangay;
    developments: Development;
    estates: Estate;
    townships: Township;
    'property-categories': PropertyCategory;
    'property-types': PropertyType;
    'property-subtypes': PropertySubtype;
    listings: Listing;
    documents: Document;
    notifications: Notification;
    'external-share-links': ExternalShareLink;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    provinces: ProvincesSelect<false> | ProvincesSelect<true>;
    cities: CitiesSelect<false> | CitiesSelect<true>;
    barangays: BarangaysSelect<false> | BarangaysSelect<true>;
    developments: DevelopmentsSelect<false> | DevelopmentsSelect<true>;
    estates: EstatesSelect<false> | EstatesSelect<true>;
    townships: TownshipsSelect<false> | TownshipsSelect<true>;
    'property-categories': PropertyCategoriesSelect<false> | PropertyCategoriesSelect<true>;
    'property-types': PropertyTypesSelect<false> | PropertyTypesSelect<true>;
    'property-subtypes': PropertySubtypesSelect<false> | PropertySubtypesSelect<true>;
    listings: ListingsSelect<false> | ListingsSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'external-share-links': ExternalShareLinksSelect<false> | ExternalShareLinksSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * User role determines access permissions (Admin only can modify)
   */
  role: 'agent' | 'approver' | 'admin';
  firstName?: string | null;
  lastName?: string | null;
  phone?: string | null;
  /**
   * Inactive users cannot log in
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Uploaded media files (images, documents)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alternative text for accessibility
   */
  alt: string;
  /**
   * User who uploaded this file
   */
  uploadedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Provinces are administrative divisions containing cities/municipalities
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "provinces".
 */
export interface Province {
  id: number;
  /**
   * Province name from PSGC API
   */
  name: string;
  /**
   * 10-digit PSGC province code
   */
  psgcCode: string;
  /**
   * Administrative region (e.g., Region X - Northern Mindanao)
   */
  region: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  /**
   * Inactive provinces will not appear in dropdowns
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Cities are the top level of the location hierarchy
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities".
 */
export interface City {
  id: number;
  name: string;
  /**
   * Province from PSGC API
   */
  province: number | Province;
  /**
   * 10-digit PSGC municipality/city code for API lookups
   */
  psgcCode: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  /**
   * Inactive cities will not appear in dropdowns
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Barangays belong to a City
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "barangays".
 */
export interface Barangay {
  id: number;
  name: string;
  /**
   * The city this barangay belongs to
   */
  city: number | City;
  /**
   * PSGC barangay code (10-digit format)
   */
  psgcCode?: string | null;
  /**
   * How this barangay record was created
   */
  sourceType?: ('seeded' | 'api_cached') | null;
  /**
   * Last time this record was synced from PSGC API
   */
  lastSyncedAt?: string | null;
  /**
   * URL-friendly identifier
   */
  slug: string;
  /**
   * Inactive barangays will not appear in dropdowns
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Developments (subdivisions) belong to a Barangay
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "developments".
 */
export interface Development {
  id: number;
  name: string;
  /**
   * The barangay this development is located in
   */
  barangay: number | Barangay;
  /**
   * Optional: Primary estate for admin clarity only (does NOT affect search logic)
   */
  primaryEstate?: (number | null) | Estate;
  /**
   * URL-friendly identifier
   */
  slug: string;
  /**
   * Inactive developments will not appear in dropdowns
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Estates are branded groupings of multiple Developments
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "estates".
 */
export interface Estate {
  id: number;
  name: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  /**
   * Developments that belong to this estate (source of truth for estate membership)
   */
  includedDevelopments: (number | Development)[];
  /**
   * Inactive estates will not appear in search filters
   */
  isActive: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * Townships are market-recognized geographic areas spanning multiple barangays
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "townships".
 */
export interface Township {
  id: number;
  name: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  /**
   * Barangays covered by this township (source of truth for township membership)
   */
  coveredBarangays: (number | Barangay)[];
  /**
   * Inactive townships will not appear in search filters
   */
  isActive: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * Property categories (e.g., Residential, Commercial)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "property-categories".
 */
export interface PropertyCategory {
  id: number;
  /**
   * Category name (e.g., Residential, Commercial)
   */
  name: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  /**
   * Optional description of this category
   */
  description?: string | null;
  /**
   * Inactive categories are hidden from selection
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Property types within categories (e.g., House, Condo)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "property-types".
 */
export interface PropertyType {
  id: number;
  /**
   * Type name (e.g., House & Lot, Condominium)
   */
  name: string;
  /**
   * Parent category this type belongs to
   */
  category: number | PropertyCategory;
  /**
   * URL-friendly identifier
   */
  slug: string;
  /**
   * Optional description of this type
   */
  description?: string | null;
  /**
   * Inactive types are hidden from selection
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Property subtypes (e.g., Studio, 2BR)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "property-subtypes".
 */
export interface PropertySubtype {
  id: number;
  /**
   * Subtype name (e.g., Studio, 1BR, 2BR)
   */
  name: string;
  /**
   * Parent type this subtype belongs to
   */
  propertyType: number | PropertyType;
  /**
   * URL-friendly identifier
   */
  slug: string;
  /**
   * Optional description of this subtype
   */
  description?: string | null;
  /**
   * Inactive subtypes are hidden from selection
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Property listings for the MLS system
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listings".
 */
export interface Listing {
  id: number;
  title: string;
  /**
   * Detailed description for internal use and client sharing
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Select category first (e.g., Residential)
   */
  propertyCategory: number | PropertyCategory;
  /**
   * Filtered by category (e.g., House & Lot)
   */
  propertyType: number | PropertyType;
  /**
   * Filtered by type (optional)
   */
  propertySubtype?: (number | null) | PropertySubtype;
  propertyOwnerName?: string | null;
  propertyOwnerContact?: string | null;
  /**
   * For agent reference only
   */
  propertyOwnerNotes?: string | null;
  /**
   * Agents can only create Resale listings
   */
  listingType: 'resale' | 'preselling';
  /**
   * Automatically set to the current user
   */
  createdBy?: (number | null) | User;
  status: 'draft' | 'submitted' | 'needs_revision' | 'published' | 'rejected';
  transactionType: 'sale' | 'rent';
  price: number;
  /**
   * Required for lot-type properties
   */
  pricePerSqm?: number | null;
  /**
   * For condos, offices, buildings
   */
  floorAreaSqm?: number | null;
  /**
   * For lots, house-and-lot
   */
  lotAreaSqm?: number | null;
  bedrooms?: number | null;
  bathrooms?: number | null;
  parkingSlots?: number | null;
  furnishing?: ('unfurnished' | 'semi_furnished' | 'fully_furnished') | null;
  constructionYear?: number | null;
  tenure?: ('freehold' | 'leasehold') | null;
  titleStatus?: ('clean' | 'mortgaged') | null;
  paymentTerms?: ('cash' | 'bank' | 'pagibig' | 'deferred')[] | null;
  /**
   * Select city first
   */
  city: number | City;
  /**
   * Filtered by selected city
   */
  barangay: number | Barangay;
  /**
   * Filtered by selected barangay (optional)
   */
  development?: (number | null) | Development;
  /**
   * Auto-populated based on Barangay
   */
  township?: (number | null) | Township;
  /**
   * Auto-populated based on Development
   */
  estate?: (number | null) | Estate;
  /**
   * Complete address for internal reference
   */
  fullAddress: string;
  /**
   * Upload listing photos
   */
  images?: (number | Media)[] | null;
  /**
   * Unit model or type name
   */
  modelName?: string | null;
  /**
   * Starting price range
   */
  indicativePriceMin?: number | null;
  /**
   * Upper price range
   */
  indicativePriceMax?: number | null;
  minLotArea?: number | null;
  minFloorArea?: number | null;
  /**
   * Standard inclusions and features
   */
  standardInclusions?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Internal notes about this preselling listing
   */
  presellingNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Documents attached to listings (titles, contracts, etc.)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  /**
   * Type of document
   */
  type:
    | 'title'
    | 'tax_declaration'
    | 'contract'
    | 'floor_plan'
    | 'site_plan'
    | 'photo_id'
    | 'proof_of_billing'
    | 'other';
  /**
   * The document file
   */
  file: number | Media;
  /**
   * The listing this document belongs to
   */
  listing: number | Listing;
  notes?: string | null;
  /**
   * Who can see this document
   */
  visibility: 'private' | 'internal';
  /**
   * Automatically set to current user
   */
  uploadedBy?: (number | null) | User;
  uploadedAt?: string | null;
  /**
   * Mark document as verified
   */
  verified?: boolean | null;
  /**
   * User who verified this document
   */
  verifiedBy?: (number | null) | User;
  verifiedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * System notifications for users
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  /**
   * Type of notification
   */
  type: 'listing_published' | 'listing_needs_revision' | 'listing_rejected' | 'listing_submitted';
  /**
   * Notification message
   */
  message: string;
  /**
   * User who receives this notification
   */
  recipient: number | User;
  /**
   * Related listing (if applicable)
   */
  listing?: (number | null) | Listing;
  /**
   * Has the user read this notification?
   */
  read?: boolean | null;
  /**
   * When the notification was read
   */
  readAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Share links for external clients to view published listings
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "external-share-links".
 */
export interface ExternalShareLink {
  id: number;
  /**
   * Auto-generated secure token for the share URL
   */
  token: string;
  /**
   * The listing to share (must be published)
   */
  listing: number | Listing;
  /**
   * User who created this share link
   */
  createdBy: number | User;
  /**
   * Optional expiry date (leave empty for no expiry)
   */
  expiresAt?: string | null;
  /**
   * Set to false to revoke this share link
   */
  isActive?: boolean | null;
  /**
   * Number of times this link has been accessed
   */
  viewCount?: number | null;
  /**
   * Last time this link was accessed
   */
  lastViewedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'provinces';
        value: number | Province;
      } | null)
    | ({
        relationTo: 'cities';
        value: number | City;
      } | null)
    | ({
        relationTo: 'barangays';
        value: number | Barangay;
      } | null)
    | ({
        relationTo: 'developments';
        value: number | Development;
      } | null)
    | ({
        relationTo: 'estates';
        value: number | Estate;
      } | null)
    | ({
        relationTo: 'townships';
        value: number | Township;
      } | null)
    | ({
        relationTo: 'property-categories';
        value: number | PropertyCategory;
      } | null)
    | ({
        relationTo: 'property-types';
        value: number | PropertyType;
      } | null)
    | ({
        relationTo: 'property-subtypes';
        value: number | PropertySubtype;
      } | null)
    | ({
        relationTo: 'listings';
        value: number | Listing;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'external-share-links';
        value: number | ExternalShareLink;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  firstName?: T;
  lastName?: T;
  phone?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  uploadedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "provinces_select".
 */
export interface ProvincesSelect<T extends boolean = true> {
  name?: T;
  psgcCode?: T;
  region?: T;
  slug?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities_select".
 */
export interface CitiesSelect<T extends boolean = true> {
  name?: T;
  province?: T;
  psgcCode?: T;
  slug?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "barangays_select".
 */
export interface BarangaysSelect<T extends boolean = true> {
  name?: T;
  city?: T;
  psgcCode?: T;
  sourceType?: T;
  lastSyncedAt?: T;
  slug?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "developments_select".
 */
export interface DevelopmentsSelect<T extends boolean = true> {
  name?: T;
  barangay?: T;
  primaryEstate?: T;
  slug?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "estates_select".
 */
export interface EstatesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  includedDevelopments?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "townships_select".
 */
export interface TownshipsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  coveredBarangays?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "property-categories_select".
 */
export interface PropertyCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "property-types_select".
 */
export interface PropertyTypesSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  slug?: T;
  description?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "property-subtypes_select".
 */
export interface PropertySubtypesSelect<T extends boolean = true> {
  name?: T;
  propertyType?: T;
  slug?: T;
  description?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listings_select".
 */
export interface ListingsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  propertyCategory?: T;
  propertyType?: T;
  propertySubtype?: T;
  propertyOwnerName?: T;
  propertyOwnerContact?: T;
  propertyOwnerNotes?: T;
  listingType?: T;
  createdBy?: T;
  status?: T;
  transactionType?: T;
  price?: T;
  pricePerSqm?: T;
  floorAreaSqm?: T;
  lotAreaSqm?: T;
  bedrooms?: T;
  bathrooms?: T;
  parkingSlots?: T;
  furnishing?: T;
  constructionYear?: T;
  tenure?: T;
  titleStatus?: T;
  paymentTerms?: T;
  city?: T;
  barangay?: T;
  development?: T;
  township?: T;
  estate?: T;
  fullAddress?: T;
  images?: T;
  modelName?: T;
  indicativePriceMin?: T;
  indicativePriceMax?: T;
  minLotArea?: T;
  minFloorArea?: T;
  standardInclusions?: T;
  presellingNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  type?: T;
  file?: T;
  listing?: T;
  notes?: T;
  visibility?: T;
  uploadedBy?: T;
  uploadedAt?: T;
  verified?: T;
  verifiedBy?: T;
  verifiedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  type?: T;
  message?: T;
  recipient?: T;
  listing?: T;
  read?: T;
  readAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "external-share-links_select".
 */
export interface ExternalShareLinksSelect<T extends boolean = true> {
  token?: T;
  listing?: T;
  createdBy?: T;
  expiresAt?: T;
  isActive?: T;
  viewCount?: T;
  lastViewedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}